server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=CST&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 6634
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pz.springcloud.domain


eureka:
  client:
    register-with-eureka: true    #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true          #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true       #访问路径可以显示IP地址